import Layout from "../components/layout";
import Head from "next/head";
import ContactUs from "../components/contact-us";

export default function Contact() {
  return (
    <div className="min-h-screen">
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ContactUs />
      </Layout>
    </div>
  );
}
