import Layout from "../components/layout";
import Hero from "../components/hero";
import Head from "next/head";

export default function Home() {
  return (
    <div className="min-h-screen">
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero />
        {/* hero section */}
        {/* what we do section */}
        {/* umfcci section */}
        {/* products we deal with section */}
      </Layout>
    </div>
  );
}
