import Layout from "../components/layout";
import Hero from "../components/hero";
import UMFCCI from "../components/umfcci";
import HowWeOperate from "../components/operate-section";
import ProductWeDeal from "../components/products-we-deal";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero />
        <UMFCCI />
        <HowWeOperate />
        <ProductWeDeal />
      </Layout>
    </div>
  );
}
