import Head from "next/head";

export default function Home() {
  return (
    <div className="bg-gray-200 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>Init Project</header>
    </div>
  );
}
