import Layout from "../components/layout";
import Head from "next/head";
import Exports from "../components/exports";
import Imports from "../components/imports";

export default function Products() {
  return (
    <div>
      <Layout>
        <Head>
          <title>Products</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Exports />
        <Imports />
      </Layout>
    </div>
  );
}
